server :
  port : 11001
spring:
  application:
    name: provider-server


#eureka配置
eureka:
    client:
        service-url: 
            #需要注册给Eureka Server的地址，也就是将自己注册给哪一个Eureka Server
            defaultZone:  http://eurekaserver13000:13000/eureka,http://eurekaserver13001:13001/eureka
    instance:
      #使用ip地址向Eureka注册
        prefer-ip-address: true        
        #上面的配置已经可以使用ip注册了，但显示的还是主机名，所以这里设置显示的注册名
        instance-id: ${spring.cloud.client.ip-address}:${server.port} 
        lease-renewal-interval-in-seconds: 5      #续约时间间隔（秒）
        lease-expiration-duration-in-seconds: 15  #续约到期时间（秒）